{"uuid": "980cddfe-c208-4e99-ac98-c8b87ba629c5", "children": ["5b08ce20-a5ec-4de8-96f2-950ea0126dd3"], "befores": [{"name": "page", "status": "passed", "start": 1755569618794, "stop": 1755569619103}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "Exception: BrowserContext.close: Connection closed while reading from the driver\n", "trace": "  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/conftest.py\", line 17, in page\n    context.close()\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py\", line 13482, in close\n    return mapping.from_maybe_impl(self._sync(self._impl_obj.close(reason=reason)))\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_browser_context.py\", line 594, in close\n    await self.request.dispose(reason=reason)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_fetch.py\", line 114, in dispose\n    await self._channel.send(\"dispose\", None, {\"reason\": reason})\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py\", line 69, in send\n    return await self._connection.wrap_api_call(\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py\", line 558, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1755569809426, "stop": 1755569809432}], "start": 1755569618794, "stop": 1755569809432}